name: skoomin
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.20
  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.10
  firebase_messaging: ^11.2.11
  firebase_storage: ^10.2.9
  file_picker: ^4.5.1
  connectivity_plus: ^2.2.1
  firebase_auth: ^3.3.11
  path_provider: ^2.0.9
  json_annotation: ^4.4.0
  badges: ^2.0.2
  reusables:
    git: 'https://github.com/ArishSultan/reusables'
  intl: ^0.17.0
  image_picker: ^0.8.4+11
  hive: ^2.1.0
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.8
  json_serializable: ^6.1.5
  hive_generator: ^1.1.2
flutter:
  uses-material-design: true
  assets:
    - assets/images/skoomin_logo.png
  fonts:
    - family: 'GoogleSans'
      fonts:
        - asset: assets/fonts/GoogleSans-Bold.ttf
        - asset: assets/fonts/GoogleSans-Regular.ttf
    - family: 'Trajan Pro'
      fonts:
        - asset: assets/fonts/TrajanPro.ttf
        - asset: assets/fonts/TrajanPro-Regular.ttf
    - family: 'Quicksand'
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf
        - asset: assets/fonts/Quicksand-Light.ttf
        - asset: assets/fonts/Quicksand-Regular.ttf
    - family: 'Lato'
      fonts:
        - asset: assets/fonts/Lato-Italic.ttf
    - family: 'Roboto'
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700